# Docker Compose cluster
# Owner: [Name]

services:
  master:
    build: .
    container_name: mini-gfs-master
    command: echo "TODO: run master server"
    ports:
      - "8000:8000"

  chunkserver1:
    build: .
    container_name: mini-gfs-chunkserver1
    command: echo "TODO: run chunkserver1"
    ports:
      - "8001:8001"

  chunkserver2:
    build: .
    container_name: mini-gfs-chunkserver2
    command: echo "TODO: run chunkserver2"
    ports:
      - "8002:8001"

  chunkserver3:
    build: .
    container_name: mini-gfs-chunkserver3
    command: echo "TODO: run chunkserver3"
    ports:
      - "8003:8001"
