services:
  master:
    build: .
    container_name: mini-gfs-master
    command: uvicorn master.main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"

  chunkserver1:
    build: .
    container_name: mini-gfs-chunkserver1
    command: uvicorn chunkserver.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  chunkserver2:
    build: .
    container_name: mini-gfs-chunkserver2
    command: uvicorn chunkserver.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8002:8001"

  chunkserver3:
    build: .
    container_name: mini-gfs-chunkserver3
    command: uvicorn chunkserver.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8003:8001"